#!/usr/bin/with-contenv bash

# Wait for MySQL to warm-up
while ! mysqladmin ping --host "$SQL_HOST" --port "${SQL_PORT:-3306}" -u"${SQL_USERNAME:-root}" -p"${SQL_PASSWORD}" --silent; do
  echo "Waiting for database to come up..."
  sleep 2
done

if ! [ -z "$API_IGNORETABLES" ] ; then
  API_IGNORETABLES="$(echo "${API_IGNORETABLES}" | tr -s "[:blank:]" "," | tr -s "," )"
  # remove beginning ,
  API_IGNORETABLES=${API_IGNORETABLES/#,}
  # remove ending ,
  API_IGNORETABLES=${API_IGNORETABLES/%,}
fi

# filter table, is a comma deliminated list: value1,value2,value3
# filtering logic
if ! [ -z "$API_FILTERTABLES" ] ; then
  if ! [ -z "$API_IGNORETABLES" ] ; then
    echo "WARNING: API_FILTERTABLES and API_IGNORETABLES specified, API_FILTERTABLES will overwrite API_IGNORETABLES"
  fi
  echo "Calculating tables to ignore"
  API_FILTERTABLES=",${API_FILTERTABLES},"
  #prepare the filtertables varible for pattern matching
  API_FILTERTABLES="$(echo ",${API_FILTERTABLES}," | tr -s "[:blank:]" "," | tr -s "," )"
  ALL_TABLES="$(mysql --host "$SQL_HOST" --port "${SQL_PORT:-3306}" -u"${SQL_USERNAME:-root}" -p"${SQL_PASSWORD}" --database "${SQL_DATABASE}" -Bse "show tables;")"
  API_IGNORETABLES=""
  for table in $ALL_TABLES; do
    if ! [[ ",${table}," =~ $API_FILTERTABLES ]]; then
      echo "${table} : added to ignorelist"
      API_IGNORETABLES="${API_IGNORETABLES},${table}"
    fi
  done
  # remove beginning ,
  API_IGNORETABLES=${API_IGNORETABLES/#,}
  # remove ending ,
  API_IGNORETABLES=${API_IGNORETABLES/%,}
fi
echo "Starting...."
exec xmysql --host "$SQL_HOST" --port "${SQL_PORT:-3306}" --database "${SQL_DATABASE}" --user "${SQL_USERNAME:-root}" --password "${SQL_PASSWORD}" --portNumber 3000 --apiPrefix "${API_PREFIX:-/api/}" --ignoreTables "${API_IGNORETABLES:-}" --storageFolder "/tmp/xmysql" --ipAddress 0.0.0.0
